### ISSUE TITLE
Lighthouse audit reports issues 

### ISSUE THREAD

**Issue by ttristan** [RyanFitzgerald/devblog#3]
I checked the demo linked in the readme with the Lighthouse audit in Chrome and it reports room for improvement. Some of those issues should be easy to fix. If I find the time this week, I will try to fix some of those.

<img width="736" alt="screen shot 2018-07-23 at 20 01 38" src="https://user-images.githubusercontent.com/24268434/43094531-834cd312-8eb3-11e8-91d9-f4f86b3e0155.png">
<img width="667" alt="screen shot 2018-07-23 at 20 01 57" src="https://user-images.githubusercontent.com/24268434/43094533-836b3a8c-8eb3-11e8-92ae-c05f588ab9cd.png">

**Comment by RyanFitzgerald** [comment]
Thanks for running that! Improving those numbers and adding some tests are definitely the next goal and if you have the time, I definitely appreciate any PRs.

**Comment by ttristan** [comment]
I got most of the stats already >90% although I struggle with "Uses document.write()". Any idea where this is coming from? I checked the [official gatsby starter blog](https://github.com/gatsbyjs/gatsby-starter-blog) and [their live-demo](http://gatsbyjs.github.io/gatsby-starter-blog/) and there it is no issue.

**Comment by RyanFitzgerald** [comment]
I took a look through the code to try and determine the source and came up empty as well. My best guess is that I have a third-party dependency containing the issue that the official starter blog does not have. I'll have to investigate further.

**Comment by ttristan** [comment]
Alight, I might have time tomorrow to track down the remaining issues. This is where I am at now:

![screen shot 2018-07-25 at 20 25 01](https://user-images.githubusercontent.com/24268434/43219965-0e0120ee-9049-11e8-8804-f090a986361f.png)
![screen shot 2018-07-25 at 20 25 09](https://user-images.githubusercontent.com/24268434/43219966-0e1dd040-9049-11e8-9d00-75f4eb5107c8.png)

This is using github pages for CDN (compression), HTTPS support etc.: https://ts-de.github.io/devblog/

I hope you do not mind the PR although it is not at 100%, yet.

**Comment by RyanFitzgerald** [comment]
That is awesome, thank you! When I get some free time tonight or tomorrow I will take a look through everything and merge the PR if there aren't any issues. At first glance it looks great.

**Comment by ttristan** [comment]
So I gave it another shot and I could fix all remaining issues by migrating gatsby v2:
![screen shot 2018-07-28 at 15 01 43](https://user-images.githubusercontent.com/24268434/43356776-6a178992-9277-11e8-8def-c7d62e3dc058.png)

I am not sure if there is any blocker for the migration, so I will create a separate PR with the new version. From what I can tell, everything is still working like before.

**Comment by ttristan** [comment]
Apparently gatsby v2 nuked the layouts and I missed to add them back in properly. I just fixed this. Now the header also should show up correctly again.
