### ISSUE TITLE
Changes for switching to styled components v4

### ISSUE THREAD

**Issue by denvercoder** [RyanFitzgerald/devblog#7]
The project wasn't working when I upgraded to styled-components v4 so I had to make a few changes.

Since 

`injectGlobal` is deprecated we have to now use `createGlobalStyle`

I removed the global-styles.js file and put all of the code into layout.js

then I just did this:

<img width="844" alt="screen shot 2019-02-15 at 10 56 14 pm" src="https://user-images.githubusercontent.com/22165183/52895260-ecc7df80-3174-11e9-8401-0f5d39a4399f.png">

everything is working again but I'm kinda new so I didn't want to submit a PR if this isn't the way it should be done.

**Comment by denvercoder** [comment]
I'll submit a PR if you want to incorporate the changes maybe make a styled-components-v4 branch???  🤷‍♂️

**Comment by marcelosevergnini** [comment]
@denvercoder I did your solution and it works well.

That part below I didn't change and it works as well too
(I removed the global-styles.js file and put all of the code into layout.js)

I think you should open the PR :)

Thanks for the help.

**Comment by RyanFitzgerald** [comment]
Sorry for the delay responding here, it seemed to have slipped through the cracks. It sounds like your solution would work, feel free to open a PR with it!
